# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home Page for Erez Karpas
email: karpase@technion.ac.il
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the website for Erez Karpas
baseurl: "/" 
url: "http://karpase.github.io" # the base hostname & protocol for your site
twitter_username: karpase
github_username:  karpase


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-scholar

# Build settings
markdown: kramdown
